# Generated by Django 5.0.6 on 2025-02-10 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maladie",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "symptoms",
                    models.TextField(
                        help_text="Liste de symptômes séparés par des virgules"
                    ),
                ),
                (
                    "traitements",
                    models.TextField(
                        help_text="Liste de traitements séparés par des virgules"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="personne_groups", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="personne_permissions",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "personne_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Health_App.personne",
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("cni", models.CharField(blank=True, max_length=20, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("Health_App.personne",),
        ),
        migrations.CreateModel(
            name="Medcin",
            fields=[
                (
                    "personne_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Health_App.personne",
                    ),
                ),
                ("specialite", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=("Health_App.personne",),
        ),
        migrations.CreateModel(
            name="Rendezvous",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_time", models.DateTimeField()),
                ("status", models.CharField(default="en attente", max_length=20)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Health_App.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PredictionDiabete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("glucose", models.FloatField()),
                ("insuline", models.FloatField()),
                ("bmi", models.FloatField()),
                ("age", models.IntegerField()),
                ("resultat", models.BooleanField()),
                ("date_prediction", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="Health_App.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("is_validate", models.BooleanField(default=False)),
                ("montant", models.FloatField()),
                (
                    "maladie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="Health_App.maladie",
                    ),
                ),
                (
                    "rendez_vous",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation",
                        to="Health_App.rendezvous",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="Health_App.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Secretaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mdp", models.CharField(max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "medcin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secretaire_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
