# Generated by Django 5.0.6 on 2025-02-11 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Health_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictionmaladiehistorique",
            name="maladie_predite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maladie_patient",
                to="Health_App.maladie",
            ),
        ),
    ]
